
BEGIN;
CREATE OR REPLACE FUNCTION update_timestamp()
RETURNS TRIGGER AS $$
BEGIN
      NEW.updated_at = now(); 
      RETURN NEW;
END;
$$ language 'plpgsql';
COMMIT;

BEGIN;
ALTER TABLE user_info ADD created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE user_info ADD updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

CREATE TRIGGER user_timestamp BEFORE INSERT OR UPDATE ON user_info
FOR EACH ROW EXECUTE PROCEDURE update_timestamp();

COMMIT;